name: multiversx_sdk
description: A comprehensive Dart library for MultiversX blockchain development, simplifying blockchain interactions for Flutter and Dart developers.
version: 0.1.2
repository: https://github.com/KLEAK-Development/multiversx

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  convert: ^3.1.0
  http: ^1.2.2
  meta: ^1.12.0
  multiversx_api: ^0.1.0
  multiversx_crypto: ^0.1.0
  pointycastle: ^3.9.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.9.0
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.0
