name: multiversx_api
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

dependencies:
  http: ^0.13.4
  json_annotation: ^4.9.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^4.0.0
  mockito: ^5.4.0
  test: ^1.25.0
