name: multiversx_api
description: A strongly-typed MultiversX API client for Dart, ensuring type safety while interacting with blockchain endpoints.
version: 0.1.2
repository: https://github.com/KLEAK-Development/multiversx

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  meta: ^1.12.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.9.0
  lints: ^5.0.0
  mockito: ^5.4.0
  test: ^1.25.0
