name: multiversx_crypto
description: A Dart package for MultiversX wallet creation, supporting mnemonic phrase generation and key pair management.
version: 0.1.2
repository: https://github.com/KLEAK-Development/multiversx

environment:
  sdk: ^3.6.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  bip39: ^1.0.6
  convert: ^3.1.1
  ed25519_hd_key: ^2.3.0
  pinenacl: ^0.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
